export const styleSheet = {
    userPage:{
        height: '200vh',
        width: '100vw',
        position:'relative',
        background:'white',
    },
    pageTopic1:{
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        top: '5%',
        position: 'relative',
    },

    formArea:{

        top:' 9%',
        left: '3%',
        width: '91%',
        height: '80%',
        margin: '1%',
        padding: '-5%',
        position: 'relative',
        background: 'pink',
        borderRadius:'10px'

    },

    firstName:{
        background: 'white',
        position:'relative',
        margin:'10px',
        width:'41%',
        display:'inline-block',
        top: '5%',
        left: '7%'
    },
    lastName:{
        background: 'white',
        position:'relative',
        margin:'10px',
        width:'41%',
        top: '5%',
        left: '7%',
        display:'inline-block',
    },
    newUsername:{
        background: 'white',
        position:'relative',
        margin:'10px',
        width:'41%',
        top: '5%',
        left: '7%',
        display:'inline-block',
    },
    newPassword:{
        background: 'white',
        position:'relative',
        margin:'10px',
        width:'41%',
        top: '5%',
        left: '7%',
        display:'inline-block',
    },
    email:{
        background: 'white',
        position:'relative',
        margin:'10px',
        width:'41%',
        display:'inline-block',
        top: '5%',
        left: '7%'
    },
    city:{
        background: 'white',
        position:'relative',
        margin:'10px',
        width:'41%',
        top: '5%',
        left: '7%',
        display:'inline-block',
    },
    street:{
        background: 'white',
        position:'relative',
        margin:'10px',
        width:'41%',
        top: '5%',
        left: '7%',
        display:'inline-block',
    },
    streetNo:{
        background: 'white',
        position:'relative',
        margin:'10px',
        width:'41%',
        top: '5%',
        left: '7%',
        display:'inline-block',
    },
    ZipCode:{
        background: 'white',
        position:'relative',
        margin:'10px',
        width:'41%',
        display:'inline-block',
        top: '5%',
        left: '7%'
    },
    latvalue:{
        background: 'white',
        position:'relative',
        margin:'10px',
        width:'41%',
        top: '5%',
        left: '7%',
        display:'inline-block',
    },
    longvalue:{
        background: 'white',
        position:'relative',
        margin:'10px',
        width:'41%',
        top: '5%',
        left: '7%',
        display:'inline-block',
    },
    mobileNo:{
        background: 'white',
        position:'relative',
        margin:'10px',
        width:'41%',
        top: '5%',
        left: '7%',
        display:'inline-block',
    },

    saveBtn1:{
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        position:'relative',
        top: '10%',
        width:'30%',
        left: '35%',
    },
    saveBtn2:{
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        position:'relative',
        top: '15%',
        width:'30%',
        left: '5%',
    },
    userTable:{
        position:'relative',
        top:'20%',
        left:'10%',
        width : '80%',

    }
}